// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/photo-layout/CircleAccent.tsx": () => import("../components/mockups/photo-layout/CircleAccent.tsx"),
  "./components/mockups/photo-layout/FullBleed.tsx": () => import("../components/mockups/photo-layout/FullBleed.tsx"),
  "./components/mockups/photo-layout/LargeLeft.tsx": () => import("../components/mockups/photo-layout/LargeLeft.tsx")
};
